[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
liquiditypool = "D84sXEooUu4FJ2EqdULee5HoELxb6Nfs1hiiLS6N73yp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "turbine-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
